//
//  WorksDetail.swift
//  iQuiz
//
//  Created by Tamires Corrêa on 12/10/25.
//

import Foundation

struct WorksDetail{
    var description: String
    var imageName: String
    var moreInfoURL: String
}

let worksDetail: [WorksDetail] = [
    WorksDetail(description: "A Catedral Metropolitana de Brasília inaugurada em 1970, é um dos marcos da capital federal. Sua arquitetura se destaca pelas colunas de concreto que sugerem mãos elevadas ao céu e pelos vitrais coloridos que proporcionam iluminação natural ao interior. Considerada uma obra-prima do modernismo brasileiro, a catedral recebe milhões de visitantes por ano e é símbolo tanto da fé quanto da inovação arquitetônica.​", imageName: "CatedralBrasilia", moreInfoURL: "https://pt.wikipedia.org/wiki/Catedral_Metropolitana_de_Bras%C3%ADlia"),
    WorksDetail(description: "O Museu Oscar Niemeyer (MON), conhecido como Museu do Olho, é o maior museu de arte da América Latina e fica em Curitiba/PR. Foi inaugurado em 22 de novembro de 2002 em um edifício originalmente concebido para uso educacional na década de 1960, mas que passou, a partir dos anos 2000, por adaptações e ganhou o anexo em formato de olho. O projeto é famoso pela sua arquitetura arrojada e inovadora, tendo o olho em estrutura de concreto que se ergue sobre pilares, proporcionando efeito escultórico e singular ao museu. Os espaços internos são amplos e moduláveis, com grandes áreas para exposições e generoso uso de luz natural por meio de imensas janelas e vitrais, que valorizam o contato entre arte e arquitetura. O conjunto arquitetônico do MON é considerado uma das obras-primas do modernismo brasileiro e marca a paisagem urbana de Curitiba.", imageName: "olho", moreInfoURL: "https://www.museuoscarniemeyer.org.br/sobre/historia"),
    WorksDetail(description: "O Edifício Copan, inaugurado em 1966, está localizado no centro de São Paulo. O prédio é reconhecido mundialmente por sua arquitetura modernista, marcada por curvas sinuosas na fachada e pela impressionante estrutura de concreto armado, rompendo com os tradicionais ângulos retos predominantes em edifícios da época. Com 32 andares e 115 metros de altura, o Copan representa uma verdadeira cidade vertical, abrigando cerca de 1.160 apartamentos e ampla oferta comercial, sendo considerado o maior edifício residencial da América Latina.​", imageName: "Copan", moreInfoURL: "https://pt.wikipedia.org/wiki/Edif%C3%ADcio_Copan"),
    WorksDetail(description: "O Congresso Nacional foi inaugurado em 21 de abril de 1960 e ocupa posição central no Eixo Monumental, em Brasília. O conjunto de arquitetura modernista destaca-se pela monumentalidade e simplicidade das formas: uma base horizontal sobre a qual se erguem as duas cúpulas — a côncava para a Câmara dos Deputados e a convexa para o Senado — e as duas torres retangulares de 28 andares, que abrigam áreas administrativas. Esse arranjo arquitetônico marca o horizonte de Brasília e simboliza a integração e independência entre os poderes legislativos do país.", imageName: "congresso", moreInfoURL: "https://pt.wikipedia.org/wiki/Congresso_Nacional_do_Brasil"),
    WorksDetail(description: "O Museu de Arte Contemporânea de Niterói (MAC), inaugurado em 2 de setembro de 1996, está localizado na orla de Niterói/RJ. Com arquitetura modernista com forte influência no futurismo, o edifício lembra um disco voador, com uma estrutura circular elevada sobre um espelho d’água e uma rampa externa na cor vermelha que conduz aos pavimentos superiores. A construção proporciona uma vista panorâmica de 360 graus para a Baía de Guanabara e as cidades vizinhas, integrando arte e paisagem de forma única.", imageName: "mac", moreInfoURL: "https://pt.wikipedia.org/wiki/Museu_de_Arte_Contempor%C3%A2nea_de_Niter%C3%B3i"),
    WorksDetail(description: "O Palácio do Planalto, inaugurado em 21 de abril de 1960 em Brasília, é um marco da arquitetura modernista. Localizado na Praça dos Três Poderes, destaca-se pelas linhas puras, formas geométricas ousadas e a fusão entre curvas e retas que conferem leveza e movimento ao edifício. Sua fachada elegante tem grandes janelas que permitem ampla entrada de luz natural, e a grande marquise sobre a entrada principal cria um ponto focal impressionante. O palácio integra-se ao entorno natural, com jardins e espaços abertos que harmonizam arquitetura e ambiente.", imageName: "palacio planalto", moreInfoURL: "https://pt.wikipedia.org/wiki/Pal%C3%A1cio_do_Planalto"),
    WorksDetail(description: "A Igreja de São Francisco de Assis, conhecida como Igreja da Pampulha, foi inaugurada em 1943 e está localizada na região da Pampulha, em Belo Horizonte/MG. Sua arquitetura modernista é notável pelas curvas e uso inovador do concreto armado, formando abóbadas parabólicas que unem estrutura e cobertura sem necessidade de alvenaria. O estilo combina fluidez e plasticidade, refletindo características do modernismo brasileiro, integrando também obras artísticas em azulejos de Cândido Portinari e paisagismo ao redor, criando um conjunto harmonioso entre arquitetura e naturez.", imageName: "pampulha", moreInfoURL: "https://pt.wikipedia.org/wiki/Igreja_de_S%C3%A3o_Francisco_de_Assis_(Belo_Horizonte)"),
    WorksDetail(description: "O Palácio da Alvorada, inaugurado em 30 de junho de 1958, é a residência oficial do Presidente da República e está localizado às margens do Lago Paranoá, em Brasília. Sua arquitetura é modernista, destacando-se pelo uso de pilotis que elevam o edifício, linhas simples e formas elegantes que promovem leveza e integração com a natureza ao redor. O palácio é composto por dois blocos principais ligados por uma passarela de vidro e é rodeado por jardins que complementam sua harmonia visual e ambiental.", imageName: "alvorada", moreInfoURL: "https://pt.wikipedia.org/wiki/Pal%C3%A1cio_da_Alvorada"),
    WorksDetail(description: "O Teatro Popular Oscar Niemeyer, inaugurado em 5 de abril de 2007, está localizado em Niterói, às margens da Baía de Guanabara, e abre o Caminho Niemeyer, um conjunto arquitetônico e cultural. Sua arquitetura modernista é marcada por uma grande cobertura curva em concreto armado, que lembra ondas do mar, e uma rampa helicoidal que conduz ao foyer, também possui azulejos amarelos na fachada oposta à Baía de Guanabara. Esses azulejos exibem pinturas e croquis feitos pelo próprio arquiteto, com desenhos alegóricos de mulheres, manifestações populares e elementos que dialogam com as curvas e formas da construção. O teatro possui palco reversível, permitindo espetáculos internos e ao ar livre para até 10 mil pessoas, integrando arte, função e espaço público de forma inovadora.", imageName: "caminho", moreInfoURL: "https://pt.wikipedia.org/wiki/Teatro_Popular_de_Niter%C3%B3i"),
    WorksDetail(description: "O Palácio do Supremo Tribunal Federal (STF), inaugurado em 21 de abril de 1960 em Brasília, é um símbolo da arquitetura modernista brasileira. Localizado na Praça dos Três Poderes, o edifício é caracterizado por sua leveza estrutural, com pilares curvos que sustentam a laje principal sem tocá-la diretamente no solo, criando uma sensação de flutuação. Seu estilo moderno se destaca pelo uso de linhas retas, fachada limpa e concreto aparente, transmitindo dignidade, simplicidade e nobreza. O STF integra o conjunto arquitetônico da nova capital, harmonizando funcionalidade e simbolismo.​", imageName: "stf", moreInfoURL: "https://www.tst.jus.br/-/projetado-por-niemeyer-tst-reflete-tracos-unicos-do-arquiteto")
]
